<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xOAdfB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xOAdfB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0xOAdfB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0xOAdfB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0xOAdfB\App_KernelDevDebugContainer([
    'container.build_hash' => '0xOAdfB',
    'container.build_id' => '179988a0',
    'container.build_time' => 1650783376,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xOAdfB');
